import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact us",
  description: "Generated by create next app",
};

const ProfilePage = () => {
  return <div>Contact us Page</div>;
};

export default ProfilePage;
