import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return <div>About Page</div>;
};

export default AboutPage;
