import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Route Group Layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {children}
      <b> Route Group layout</b>
    </div>
  );
}
